
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2022 Lukas <lumip> Prediger

name: Build Binaries

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*stable" ]

jobs:
  build-binaries:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build GUI as single file executable
        run: dotnet publish -r win-x64 -c Release --self-contained false /p:PublishSingleFile=true ./MSFSModManager.GUI/
      - name: Upload GUI binaries.
        uses: actions/upload-artifact@v3
        with:
          name: fsmodm-gui
          path: |
            MSFSModManager.GUI/bin/Release/net5.0/win-x64/publish/*.exe
            MSFSModManager.GUI/bin/Release/net5.0/win-x64/publish/*.dll
            MSFSModManager.GUI/bin/Release/net5.0/win-x64/publish/*.config
          if-no-files-found: error
          retention-days: 14
      - name: Build CLI as single file executable
        run: dotnet publish -r win-x64 -c Release --self-contained false /p:PublishSingleFile=true ./MSFSModManager.CLI/
      - name: Upload CLI binaries.
        uses: actions/upload-artifact@v3
        with:
          name: fsmodm-cli
          path: |
            MSFSModManager.CLI/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
            MSFSModManager.CLI/bin/Release/netcoreapp3.1/win-x64/publish/*.dll
            MSFSModManager.CLI/bin/Release/netcoreapp3.1/win-x64/publish/*.config
          if-no-files-found: error
          retention-days: 14
