
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2022 Lukas <lumip> Prediger

name: Create Pre-Release

on:
  push:
    tags: [ '*' ]

jobs:
  build-binaries:
    uses: ./.github/workflows/build_binaries.yml

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build-binaries
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: binaries
      - name: Bundle ZIPs
        run: |
          cd binaries
          zip -r fsmodm-cli.zip fsmodm-cli
          zip -r fsmodm-gui.zip fsmodm-gui
      - name: Publish Pre-Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF##refs/tags/}
          echo "Version: ${VERSION}"
          echo "Ref: ${GITHUB_REF}"
          echo "Tag: ${TAG_NAME}"
          assets=()
          for asset in $(find wheels -type f); do
            echo "Adding asset: ${asset}"
            assets+=("-a" "$asset")
          done
          hub release create -p -a binaries/fsmodm-cli.zip -a binaries/fsmodm-gui.zip -m "$TAG_NAME" "$TAG_NAME"
